### ISSUE TITLE
Additional Jar option not working with Forge

### ISSUE THREAD

**Issue by stephenmac7** [RobertZenz/EasyMineLauncher#8]
It seems that using these options:

```
java -jar launch.jar --jar-dir=bin/ --native-dir=bin/natives/ --parent-dir=$(pwd)/ --additional-jar=minecraftforge-universal-1.5.2-7.8.1.738.zip
```

EasyMineLauncher crashes with a java.lang.NoClassDefFoundError:

```
Loading natives from: /home/stephen/Development/testm/bin/natives
Loading Minecraft from: /home/stephen/Development/testm/bin/minecraft.jar
Exception in thread "main" java.lang.NoClassDefFoundError: avu
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2413)
    at java.lang.Class.getConstructor0(Class.java:2723)
    at java.lang.Class.newInstance0(Class.java:345)
    at java.lang.Class.newInstance(Class.java:327)
    at org.bonsaimind.easyminelauncher.ContainerApplet.loadJarsAndApplet(Unknown Source)
    at org.bonsaimind.easyminelauncher.Main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: avu
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 7 more
```

It does, however, work without the additional-jar option.

**Comment by RobertZenz** [comment]
The only file with the name [`minecraftforge-src-1.5.2-7.8.1.738.zip`](http://files.minecraftforge.net/minecraftforge/minecraftforge-src-1.5.2-7.8.1.738.zip) is a complete package of the mod. You can't specify that with the `--additional-jar` option as it is not a valid Java jar. You'll have to extract it and install it properly and then see what is necessary to be loaded additionally to the minecraft.jar.

Or did I miss something here?

**Comment by stephenmac7** [comment]
It is `minecraftforge-universal-1.5.2-7.8.1.738.zip`, not `minecraftforge-src-1.5.2-7.8.1.738.zip`. It only includes the files which need to be added to the Minecraft.jar. It works when the files inside are copied directly to the root of the Minecraft jar file (in 1.5.2, I have no idea how 1.6.1 works).

**Comment by RobertZenz** [comment]
My apologize. I should start quoting my Google searches...

Anyway, if I see this correctly, that zip is meant to be copied into the minecraft.jar, overriding parts of it. It can not be loaded via the `--additional-jar` option.

_But_ I could provide a `--blend` option which copies these two together at runtime, if you might find that useful.

**Comment by stephenmac7** [comment]
That would be extremely useful, to anyone who uses Minecraft Forge. It would allow dynamic loading of minecraft forge, removing the step of adding it into the jar.

**Comment by RobertZenz** [comment]
0.16 is ready for download and provides such an option.

Feel free to open new bug reports as necessary.

**Comment by stephenmac7** [comment]
Thank you so much! It works perfectly.
