### ISSUE TITLE
Precompiled Jars will not run on Mac Mountain Lion

### ISSUE THREAD

**Issue by stephenmac7** [RobertZenz/EasyMineLauncher#9]
The title says it all. Here is the error:

``` java
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/bonsaimind/easyminelauncher/Main : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

Also can't compile manually:

``` java
src/org/bonsaimind/easyminelauncher/Main.java:491: cannot find symbol
symbol  : method setOpacity(float)
location: class org.bonsaimind.easyminelauncher.ContainerFrame
            frame.setOpacity(opacity);
                 ^
1 error
```

**Comment by RobertZenz** [comment]
Can you please provide the output of

```
java -version
```

It sounds like you're running on 1.6 (or even older) but I compiled it with 1.7.

As for manual compilation, it really sounds like you're on a version I did not account for. You could compile it by simply commenting out the line 491. Or here as a patch:

```
diff --git a/src/org/bonsaimind/easyminelauncher/Main.java b/src/org/bonsaimind/easyminelauncher/Main.java
index 01b4e80..9ffa57f 100644
--- a/src/org/bonsaimind/easyminelauncher/Main.java
+++ b/src/org/bonsaimind/easyminelauncher/Main.java
@@ -488,7 +488,7 @@ public class Main {

                if (opacity < 1) {
                        frame.setUndecorated(true);
-                       frame.setOpacity(opacity);
+                       //frame.setOpacity(opacity);
                }

                frame.setContainerApplet(container);
```

**Comment by RobertZenz** [comment]
Can you try 1.6.1? I recompiled the jar to be compatible with 1.5 upwards. If I see this right your MacOS still has 1.6.

**Comment by stephenmac7** [comment]
Sure, however I can't do that now. Maybe in a week or two.

**Comment by RobertZenz** [comment]
Did you find the time to try it?
